<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getItems())) {
    $type = 'widget-new-list';

    $mode = 'list';
    $widgetType = $block->getProductTypes();

    $image = 'new_products_content_widget_list';
    $title = $block->getTitle();
    $items = $block->getProductCollection()->getItems();
    $label = $block->getWidgetLabel();
    $isCarousel = $block->getShowCarousel();
    $visibleCarousel = $block->getNumberToDisplay();
    $productItemWidth = $block->getItemWidth();
    $cssClass = $block->getCssClass();

    $showReviews = [
        'new_product'         => false,
        'sale_product'        => false,
        'viewed_product'      => false,
        'bestsellers_product' => false,
        'rated_product'       => true,
        'manual_product'      => false
    ];

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
}
?>

<?php ?>

<?php if ($exist):?>
    <div class="block widget featured <?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $widgetType; ?> <?php /* @escapeNotVerified */ echo $cssClass; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __($title); ?></strong>
        </div>
        <div class="block-content<?php echo $productItemWidth ? ' custom-columns' : '' ?>">
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="product-items <?php /* @escapeNotVerified */ echo $type; ?>"
                    <?php if ($isCarousel): ?>
                        data-mage-init='{"faeturedCarousel": {"items": "<?php /* @escapeNotVerified */ echo $visibleCarousel; ?>"}}'
                    <?php endif; ?>>
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="product-item"' . ' ' . $productItemWidth . '>'
                            : '</div><div class="product-item"' . ' ' . $productItemWidth . '>' ?>
                        <?php /* @escapeNotVerified */ echo ($block->getShowLabel()) ? '<span class="product-label">' . $label . '</span>' : ''; ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <?php echo /* @escapeNotVerified */ $block->getProductPriceHtml($_item, $type); ?>
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->truncateProductName($_item->getName()); ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, $showReviews[$widgetType]) ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
