<?php
$columnNumber = 3;
?>

<?php if ($posts = $this->getPosts()) : ?>
    <div class="block widget blog-posts">
        <h1 class="page-title">
            <strong><?php echo __('From the Blog') ?></strong>
        </h1>
        <div class="block-content">
            <div class="post-items">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <?php if ($image = $post->getImage()): ?>
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $image ?>" /></a>
                        </div>
                        <?php endif; ?>

                        <!-- Title -->
                        <div class="post-title">
                            <h3>
                                <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                            </h3>
                        </div>

                        <!-- Short Description -->
                        <div class="post-short-content">
<!--                            --><?php //echo $block->filterContent($post->getShortContent()); ?>
                            <?php  ?>
                            <?php if (strlen($block->filterContent($post->getShortContent())) > 120): ?>
                                <?php echo substr($block->filterContent($post->getShortContent()), 0, 120); ?>
                                    ...
                            <?php else: ?>
                                <?php echo $block->filterContent($post->getShortContent()); ?>
                            <?php endif; ?>
                        </div>

                        <!-- Metadata -->
                        <div class="post-data">
                            <?php if ($post->getCommentsEnabled()) : ?>
                                <span class="post-comments">
                                    <?php if ($post->getApprovedComments()->count() > 0): ?>
                                        <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                            <span class="count">
                                                <?php echo $post->getApprovedComments()->count(); ?>
                                            </span>
                                        </a>
                                    <?php else: ?>
                                        <span class="count no-comment">
                                            <?php /* @escapeNotVerified */ echo __('0'); ?>
                                        </span>
                                    <?php endif; ?>
                                </span>
                            <?php endif; ?>
                            <span class="create-date material-icons-access_time">
                                <time><?php echo $block->formatDate($post->getCreationTime(), 2, false);?></time>
                            </span>
                            <?php if ($author = $post->getAuthor()): ?>
                                <span class="post-author material-icons-person">
                                    <span class="label"><?php echo __('by '); ?></span>
                                    <span class="author"><?php echo $author; ?></span>
                                </span>
                            <?php endif; ?>
                        </div>
                        <a href="<?php echo $this->getPostUrl($post); ?>" class="post-button">
                            <span><?php /* @escapeNotVerified */ echo __('Read More'); ?></span>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>