<div class="container">
    <ul class="list-2">
        <li>
            <span class="icons-list-2 fa fa-truck"></span>
            <h4 class="title-list-2">Shipping & Delivery</h4>
            <div class="desc-list-2">Here you can read some details about a nifty little lifecycle of your order's journey from the time you place your order to your new treasures arriving at your doorstep. Product packaging, printing labels, information about tracking your orders can be found in this section.</div>
        </li>
        <li>
            <span class="icons-list-2 fa fa-credit-card"></span>
            <h4 class="title-list-2">Payment Methods</h4>
            <div class="desc-list-2">It is equally important to choose the solution which offers a specific selection of credit cards that are most popular in the merchants target markets. We take Visa & MasterCard as they are widely used by cyber customers.</div>
        </li>
        <li>
            <span class="icons-list-2 fa fa-envelope-o"></span>
            <h4 class="title-list-2">Contact us</h4>
            <div class="desc-list-2">You can contact us any way that is convenient for you. We are available 24/7 via fax, email or telephone. You can also use a quick contact form or visit our office personally.<a class="button" title="contact with us" href="{{store url=''}}contacts"><span><span>contact with us</span></span></a></div>

        </li>
    </ul>
</div>